---
title: "Honey Bees (Apis mellifera Linnaeus) Spatial Analysis"
author: "Alyssa Foote, Noman Mohammad, and Vimaljeet Singh"
date: "2023-04-03"
output:
  pdf_document:
    dev: png
fontsize: 12pt
---

```{r global_options, include=FALSE, cache=FALSE}
## Set some options for knitr to apply globally
knitr::opts_chunk$set(cache=TRUE,
                      echo=FALSE,
                      autodep=TRUE,
                      message=FALSE,
                      warning=FALSE,
                      out.width="80%",
                      fig.asp=0.75,
                      fig.align='center')
```

# Introduction - Noman

Provide a brief description of the study system from which the data come and an outline of what questions you intend on exploring with the data, citing any relevant literature. Length: ca. 1 page.

# Methods - All, see subsections

There should be enough information that anyone can reproduce the workflow if they had access to the data. Length: As long as necessary.

## Data collection and Description - Noman
Briefly describe the data and what variables are included.

## Exploratory Analysis - Vimal

Provide a detailed description of the analytical workflow that was applied to the data, citing any relevant literature and statistical packages employed. 

## Model Selection - Alyssa

Provide a detailed description of the analytical workflow that was applied to the data, citing any relevant literature and statistical packages employed. 

# Results
## Exploratory Analysis - Vimal
Describe your statistical findings. Tables and figures should be used throughout. Length: As long as necessary.

## Model Selection - Alyssa
Describe your statistical findings. Tables and figures should be used throughout. Length: As long as necessary.

# Discussion - Vimal and Alyssa

Provide a brief summary of your findings. Length: ca. 1 page.

# References - All

Include references to all necessary literature.